version: "3.7"
services:
  php:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      target: dev
    container_name: php
    volumes:
      - monitor_home:/home/zalex
      - "..:/usr/src/app"
      - ~/.composer:/home/zalex/.composer
  prod:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      target: prod
    container_name: monitor-prod
    volumes:
      - monitor_home:/home/zalex
      - ~/.composer:/home/zalex/.composer
      - /tmp:/tmp
volumes:
  monitor_home:
